name: 'Label Checker'
description: 'Checks labels on PRs'
icon: 'tag'
colour: 'orange'
inputs:
  labels: 
    description: 'Comma seperated list of labels to check'
    required: true
    default: ''
outputs:
  pass: 
    description: 'Was the label present'
runs:
  using: 'node16'
  main: 'index.js'
